"""Adicionado Tabela 'atendimentos' e devidas relacoes

Revision ID: 0666c174233c
Revises: 7ca1b9aecc3c
Create Date: 2026-04-23 11:35:07.697170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0666c174233c'
down_revision: Union[str, Sequence[str], None] = '7ca1b9aecc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('horario_chegada', sa.DateTime(), nullable=True),
    sa.Column('horario_triagem', sa.DateTime(), nullable=True),
    sa.Column('horario_atendimento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.add_column('pacientes', sa.Column('data_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'data_nascimento')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_table('atendimentos')
    # ### end Alembic commands ###
