"""unidades_detalhadas_com_url_imagem

Revision ID: 3ddc963e2330
Revises: 7f41bdb92627
Create Date: 2026-05-12 01:28:25.812350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ddc963e2330'
down_revision: Union[str, Sequence[str], None] = '7f41bdb92627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('imagem_url', sa.String(), nullable=True))
    op.drop_column('unidades', 'imagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('imagem', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('unidades', 'imagem_url')
    # ### end Alembic commands ###
