"""refatoracao_mapeamento_sqlalchemy_20

Revision ID: 58bcd66d0618
Revises: 0666c174233c
Create Date: 2026-05-11 22:35:42.617814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '58bcd66d0618'
down_revision: Union[str, Sequence[str], None] = '0666c174233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
