"""nome_da_migracao

Revision ID: 6f2210f2dfa3
Revises: 58bcd66d0618
Create Date: 2026-05-12 01:14:28.392769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f2210f2dfa3'
down_revision: Union[str, Sequence[str], None] = '58bcd66d0618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('tipo', sa.String(), nullable=False))
    op.add_column('unidades', sa.Column('numero', sa.String(), nullable=True))
    op.add_column('unidades', sa.Column('complemento', sa.String(), nullable=True))
    op.add_column('unidades', sa.Column('cep', sa.String(), nullable=True))
    op.add_column('unidades', sa.Column('cidade', sa.String(), nullable=False))
    op.add_column('unidades', sa.Column('estado', sa.String(), nullable=False))
    op.add_column('unidades', sa.Column('telefone1', sa.String(), nullable=False))
    op.add_column('unidades', sa.Column('telefone2', sa.String(), nullable=True))
    op.add_column('unidades', sa.Column('descricao', sa.String(), nullable=True))
    op.add_column('unidades', sa.Column('horario_funcionamento', sa.String(), nullable=True))
    op.alter_column('unidades', 'localizacao',
               existing_type=Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=False)
    op.drop_column('unidades', 'imagem')
    op.drop_column('unidades', 'tempo_medio_minutos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('tempo_medio_minutos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('unidades', sa.Column('imagem', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('unidades', 'localizacao',
               existing_type=Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               nullable=True)
    op.drop_column('unidades', 'horario_funcionamento')
    op.drop_column('unidades', 'descricao')
    op.drop_column('unidades', 'telefone2')
    op.drop_column('unidades', 'telefone1')
    op.drop_column('unidades', 'estado')
    op.drop_column('unidades', 'cidade')
    op.drop_column('unidades', 'cep')
    op.drop_column('unidades', 'complemento')
    op.drop_column('unidades', 'numero')
    op.drop_column('unidades', 'tipo')
    # ### end Alembic commands ###
