"""Adicionado campo 'imagem' em Unidade

Revision ID: 7ca1b9aecc3c
Revises: 9addfcb1813c
Create Date: 2026-04-23 10:55:29.376823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7ca1b9aecc3c'
down_revision: Union[str, Sequence[str], None] = '9addfcb1813c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('imagem', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unidades', 'imagem')
    # ### end Alembic commands ###
