"""unidades_detalhadas_com_imagem

Revision ID: 7f41bdb92627
Revises: 6f2210f2dfa3
Create Date: 2026-05-12 01:19:12.898122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7f41bdb92627'
down_revision: Union[str, Sequence[str], None] = '6f2210f2dfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('imagem', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unidades', 'imagem')
    # ### end Alembic commands ###
